name: hestia
description: "Manten Privada, tu Privada"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  auto_route: ^9.2.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_boxicons: ^3.1.0
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/